### ISSUE TITLE
Inconsistent test results in github vs legend-base

### ISSUE THREAD

**Issue by jasondet** [legend-exp/pygama#327] opened 2022-07-26 16:20 UTC
github is happy passing all tests. however in legend-base on the lngs server, the tests die on importing orca_packet with:

```
raw/orca/orca_packet.py:15
ERROR test_orca_packet.py - TypeError: 'numpy._DTypeMeta' object is not subscriptable
```

I suspect we are missing a required version dependency for annotations?

**Comment by gipert** [comment] 2022-07-26 17:45
Might be due to an incompatible numpy version... Will check and fix once I'm back online.

We had to disable testing with the container because our image is too heavy to be downloaded on the GitHub action runners

**Comment by gipert** [comment] 2022-08-01 11:43
DSP tests are failing in the container:
```console
$ pytest tests/dsp
ImportError while loading conftest '/tmp/pygama/tests/dsp/conftest.py'.
tests/dsp/conftest.py:3: in <module>
    import pygama.dsp.processors  # noqa: F401
/user/.local/lib/python3.9/site-packages/pygama/dsp/__init__.py:20: in <module>
    from .build_dsp import build_dsp
/user/.local/lib/python3.9/site-packages/pygama/dsp/build_dsp.py:21: in <module>
    from pygama.dsp.processing_chain import build_processing_chain
/user/.local/lib/python3.9/site-packages/pygama/dsp/processing_chain.py:23: in <module>
    from pygama.math.units import Quantity, Unit
/user/.local/lib/python3.9/site-packages/pygama/math/units.py:1: in <module>
    from pint import Measurement, Quantity, Unit, UnitRegistry, set_application_registry
/user/.local/lib/python3.9/site-packages/pint/__init__.py:16: in <module>
    from .context import Context
/user/.local/lib/python3.9/site-packages/pint/context.py:20: in <module>
    from .definitions import Definition, UnitDefinition
/user/.local/lib/python3.9/site-packages/pint/definitions.py:16: in <module>
    from .converters import Converter, LogarithmicConverter, OffsetConverter, ScaleConverter
/user/.local/lib/python3.9/site-packages/pint/converters.py:12: in <module>
    from .compat import HAS_NUMPY, exp, log  # noqa: F401
/user/.local/lib/python3.9/site-packages/pint/compat.py:163: in <module>
    from xarray import DataArray, Dataset, Variable
/opt/anaconda3/lib/python3.9/site-packages/xarray/__init__.py:1: in <module>
    from . import testing, tutorial, ufuncs
/opt/anaconda3/lib/python3.9/site-packages/xarray/testing.py:8: in <module>
    from xarray.core import duck_array_ops, formatting, utils
/opt/anaconda3/lib/python3.9/site-packages/xarray/core/duck_array_ops.py:24: in <module>
    from . import dask_array_compat, dask_array_ops, dtypes, npcompat, nputils
/opt/anaconda3/lib/python3.9/site-packages/xarray/core/dask_array_compat.py:5: in <module>
    from .pycompat import dask_version
/opt/anaconda3/lib/python3.9/site-packages/xarray/core/pycompat.py:55: in <module>
    dsk = DuckArrayModule("dask")
/opt/anaconda3/lib/python3.9/site-packages/xarray/core/pycompat.py:22: in __init__
    duck_array_version = LooseVersion(duck_array_module.__version__)
/opt/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/version.py:53: in __init__
    warnings.warn(
E   DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
```
and seems to be related to Pint.

CC @iguinn

**Comment by oschulz** [comment] 2022-08-01 17:57
> can you reproduce this with the current pygama

Do you mean reproduce with the current container, or an updated one with a current xarray?

**Comment by gipert** [comment] 2022-08-01 18:00
I mean with the latest container and the latest pygama commit (on `main`). You would need to first `pip install .[test]` and then `pytest`.

**Comment by oschulz** [comment] 2022-08-02 09:57
I can make that part of the container build, I think.

**Comment by gipert** [comment] 2022-08-04 10:17
> I can make that part of the container build, I think.

Ok, so the test suite runs just fine? Can we close this?

**Comment by oschulz** [comment] 2022-08-04 21:04
Haven't run it yet, have to rebuild the containers first the next days.

**Comment by oschulz** [comment] 2022-10-24 10:41
pygama tests pass now in the legend-software container and are part of the container build.

**Closed by oschulz** 2022-10-24 10:41 UTC
Labels: bug, dsp, raw

**Comment by gipert** [comment] 2022-10-25 13:52
@oschulz why ignoring the deprecation warning?

https://github.com/legend-exp/legendexp_legend-software_img/blob/master/provisioning/install-sw-scripts/pygama-setup.sh#L20

I think the right solution would be to get a more recent xarray version, as I mentioned earlier in this thread: https://github.com/legend-exp/pygama/issues/327#issuecomment-1201148339. Isn't it possible?

**Comment by oschulz** [comment] 2022-10-26 07:21
Well, it would be nice to be able to go with regular Anaconda releases in general, and not always have to do specific updates for individual packages. Will this xarray thing result in reduced performance or is it just a pure deprecation warning?

As far as I know, `ignore::DeprecationWarning` is not uncommon in Python production testing.

**Comment by gipert** [comment] 2022-10-26 07:29
No, it's not a big issue. I agree we should stick to Anaconda stable releases, even if I don't like suppressing indiscriminately all deprecation warnings...

Let's hope it will go away by itself at some point.

**Comment by oschulz** [comment] 2022-10-26 07:33
Ok :-)
