### ISSUE TITLE
Support numba v0.54.0

### ISSUE THREAD

**Issue by oschulz** [legend-exp/pygama#218] opened 2021-12-02 06:55 UTC
pygama currently limits numba<=0.52.0, this blocks updating to Anaconda 2021.11 which [provides numba v0.54.1](https://docs.anaconda.com/anaconda/packages/py3.9_linux-64/).

**Comment by oschulz** [comment] 2021-12-02 09:39
@gipert pointed out the the numba version limite was introduced in #193 due to numba/numba#7402.

That numba issue has been fixed in numba/numba#7403, but it's tagged with the numba v0.55 milestone, so it may be a while before it's release.

Can we work around numba/numba#7402? Would be annoying if this would block us from supporting current Anaconda releases.

**Comment by oschulz** [comment] 2021-12-02 10:06
Numba v0.52.0 is not compatible with Python v3.9.0, so this blocks using Python 3.9 in general.

**Comment by iguinn** [comment] 2021-12-02 14:37
I don't think there is a simple workaround for this. The problem is that they accidentally removed some of the important information about the function signature that is expected from @guvectorize. We could work around this by manually adding this information to each processor, but this would be a lot of work and would introduce a lot of opportunity for errors. Numba seems to be on a ~6 month release cycle for major versions, so I think we'll see v0.55, which will include the fix, around March. How important is it to support python v3.9 right now?

**Comment by wisecg** [comment] 2021-12-03 00:21
It's really not a high priority IMO.  @oschulz  is right that we should have a software stack flexible enough to build pygama along with some of our other requirements.  I agree that we should just revisit this issue when numba 0.55 comes out, and stay with python 3.8 in the legend containers until then.

**Comment by iguinn** [comment] 2022-02-18 20:14
This has been resolved in this pull request: https://github.com/legend-exp/pygama/pull/227. While we still can't support v0.54 or v0.53, we do support all other versions

**Closed by iguinn** 2022-02-18 20:14 UTC
Labels: enhancement
